### ISSUE TITLE
test cases

### ISSUE THREAD

**Issue by snowsky** [nsjames/Hack-Til-Dawn#13]
Hi James,

Thanks for the smart contracts. I think that would be great if you can put up some test cases for the contracts at your convenience.

Cheers,
Hao

**Comment by nsjames** [comment]
This actually has a full suite here:
https://github.com/nsjames/scatter-hackathon/blob/master/test/contract.spec.js

I did it on the front-end to kill two birds with 1 stone, but you're right the contract should have it's own set of unit tests.

**Comment by snowsky** [comment]
Thanks @nsjames. It is what I am looking for. Let me close the issue.
